<?php

declare(strict_types=1);

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');
@set_time_limit(0);

function respond(int $status, array $payload): never
{
    http_response_code($status);
    echo json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
    exit;
}

function run_cmd(string $cwd, string $command, ?int &$exitCode = null): string
{
    $lines = [];
    $code = 0;
    exec('cd ' . escapeshellarg($cwd) . ' && ' . $command . ' 2>&1', $lines, $code);
    $exitCode = $code;
    return trim(implode("\n", $lines));
}

function php_cli(): string
{
    // Under php-fpm, PHP_BINARY points at the FPM binary, which cannot run a
    // script. Prefer it only when it is a usable CLI; otherwise locate one.
    $binary = PHP_BINARY;
    if ($binary !== '' && is_executable($binary) && !preg_match('/php-?fpm/i', basename($binary))) {
        return $binary;
    }
    $candidates = [PHP_BINDIR . '/php', '/usr/bin/php', '/usr/local/bin/php', '/bin/php'];
    foreach ($candidates as $candidate) {
        if (is_file($candidate) && is_executable($candidate)) {
            return $candidate;
        }
    }
    return 'php';
}

function php_command(string $script, string ...$args): string
{
    $parts = [escapeshellarg(php_cli()), escapeshellarg($script)];
    foreach ($args as $arg) {
        $parts[] = escapeshellarg($arg);
    }
    return implode(' ', $parts);
}

function runtime_secret_path(string $root): string
{
    return $root . '/data/dni-runtime.env';
}

function configured_star_comms_shard(string $root): string
{
    $fallback = 'https://s-dreadnought-imperium.star-comms.org';
    $configPath = $root . '/configs/star-comms.config.json';
    if (!is_file($configPath)) {
        return $fallback;
    }

    $raw = file_get_contents($configPath);
    if ($raw === false) {
        return $fallback;
    }

    $config = json_decode($raw, true);
    $candidate = is_array($config) ? trim((string)($config['shardUrl'] ?? '')) : '';
    if ($candidate === '' || !filter_var($candidate, FILTER_VALIDATE_URL)) {
        return $fallback;
    }

    $parts = parse_url($candidate);
    $scheme = strtolower((string)($parts['scheme'] ?? ''));
    $host = strtolower((string)($parts['host'] ?? ''));
    if ($scheme !== 'https' || ($host !== 'star-comms.org' && !str_ends_with($host, '.star-comms.org'))) {
        return $fallback;
    }

    return rtrim($candidate, '/');
}

function sync_repository_secrets(string $root, string $method): array
{
    $path = runtime_secret_path($root);
    $present = is_file($path) && filesize($path) !== false && filesize($path) > 0;

    if ($method !== 'POST') {
        return ['configured' => $present, 'updated' => false];
    }

    $ownerKey = trim((string)($_SERVER['HTTP_X_DNI_STAR_COMMS_OWNER_KEY'] ?? ''));
    if ($ownerKey === '') {
        // Manual deploys are allowed to omit the header. Never erase an
        // already-synchronized repository secret just because it was omitted.
        return ['configured' => $present, 'updated' => false];
    }

    if (!preg_match('/^scok_[A-Za-z0-9_-]+$/D', $ownerKey)) {
        throw new RuntimeException('STAR_COMMS_OWNER_KEY supplied by deployment is not a valid Owner API key.');
    }

    $directory = dirname($path);
    if (!is_dir($directory) && !mkdir($directory, 0750, true) && !is_dir($directory)) {
        throw new RuntimeException('Unable to create the private DNI runtime data directory.');
    }

    $shard = configured_star_comms_shard($root);
    $contents = "# Generated by DNI GitHub Actions deployment. Do not commit.\n"
        . 'STAR_COMMS_SHARD_URL=' . $shard . "\n"
        . 'STAR_COMMS_OWNER_KEY=' . $ownerKey . "\n";

    $temporary = $path . '.tmp.' . getmypid();
    if (file_put_contents($temporary, $contents, LOCK_EX) === false) {
        throw new RuntimeException('Unable to write the private DNI runtime secret file.');
    }

    @chmod($temporary, 0600);
    if (!rename($temporary, $path)) {
        @unlink($temporary);
        throw new RuntimeException('Unable to activate the private DNI runtime secret file.');
    }
    @chmod($path, 0600);

    return ['configured' => true, 'updated' => true];
}

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
if ($method !== 'GET' && $method !== 'POST') {
    respond(405, ['ok' => false, 'error' => 'Use GET or POST.']);
}

$disabled = array_filter(array_map('trim', explode(',', (string)ini_get('disable_functions'))));
if (!function_exists('exec') || in_array('exec', $disabled, true)) {
    respond(500, ['ok' => false, 'error' => 'PHP exec() is disabled on this LAMP server.']);
}

$root = realpath(__DIR__ . '/..');
if ($root === false || !is_dir($root . '/.git')) {
    respond(500, ['ok' => false, 'error' => 'DNI repository checkout was not found behind the Apache document root.']);
}

$builder = $root . '/scripts/build-lamp.php';
if (!is_file($builder)) {
    respond(500, ['ok' => false, 'error' => 'DNI LAMP build helper was not found.']);
}

$lockPath = rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . 'dni-deploy.lock';
$lock = fopen($lockPath, 'c');
if ($lock === false || !flock($lock, LOCK_EX | LOCK_NB)) {
    respond(409, ['ok' => false, 'status' => 'in-progress', 'message' => 'A DNI deployment is already running.']);
}

$startedAt = gmdate('c');

try {
    $secretState = sync_repository_secrets($root, $method);

    $output = run_cmd($root, 'git checkout -- public/index.html public/dist', $code);
    if ($code !== 0) {
        throw new RuntimeException('Unable to reset generated web assets: ' . $output);
    }

    $output = run_cmd($root, 'git fetch --quiet origin main', $code);
    if ($code !== 0) {
        throw new RuntimeException('git fetch failed: ' . $output);
    }

    $local = trim(run_cmd($root, 'git rev-parse HEAD', $code));
    if ($code !== 0 || !preg_match('/^[0-9a-f]{40}$/', $local)) {
        throw new RuntimeException('Unable to resolve the live commit.');
    }

    $remote = trim(run_cmd($root, 'git rev-parse origin/main', $code));
    if ($code !== 0 || !preg_match('/^[0-9a-f]{40}$/', $remote)) {
        throw new RuntimeException('Unable to resolve origin/main.');
    }

    if ($local === $remote) {
        $output = run_cmd(
            $root,
            php_command('scripts/build-lamp.php', '.', substr($local, 0, 12)),
            $code
        );
        if ($code !== 0) {
            throw new RuntimeException('LAMP asset refresh failed: ' . $output);
        }

        respond(200, [
            'ok' => true,
            'status' => 'current',
            'changed' => false,
            'commit' => $local,
            'startedAt' => $startedAt,
            'completedAt' => gmdate('c'),
            'runtime' => 'rocky9-lamp',
            'starCommsSecretConfigured' => $secretState['configured'],
            'starCommsSecretUpdated' => $secretState['updated'],
            'message' => 'DNI Apache/PHP deployment is already current with origin/main.'
        ]);
    }

    run_cmd(
        $root,
        'git merge-base --is-ancestor ' . escapeshellarg($local) . ' ' . escapeshellarg($remote),
        $code
    );
    if ($code !== 0) {
        throw new RuntimeException('Refusing deployment because origin/main is not a fast-forward of the live checkout.');
    }

    $candidate = rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR)
        . DIRECTORY_SEPARATOR
        . 'dni-deploy-' . substr($remote, 0, 12) . '-' . getmypid();

    run_cmd($root, 'rm -rf ' . escapeshellarg($candidate), $code);
    $output = run_cmd(
        $root,
        'git worktree add --detach ' . escapeshellarg($candidate) . ' ' . escapeshellarg($remote),
        $code
    );
    if ($code !== 0) {
        throw new RuntimeException('Unable to create candidate worktree: ' . $output);
    }

    try {
        $checks = [
            php_command('scripts/build-lamp.php', '.', substr($remote, 0, 12)),
            escapeshellarg(php_cli()) . ' -l public/deploy.php',
            escapeshellarg(php_cli()) . ' -l deploy/ovhcloud/configure-httpd-vhost.php',
        ];
        foreach ($checks as $command) {
            $output = run_cmd($candidate, $command, $code);
            if ($code !== 0) {
                throw new RuntimeException('Candidate LAMP verification failed during ' . $command . ': ' . $output);
            }
        }
    } finally {
        run_cmd($root, 'git worktree remove --force ' . escapeshellarg($candidate), $cleanupCode);
        if ($cleanupCode !== 0) {
            run_cmd($root, 'rm -rf ' . escapeshellarg($candidate), $cleanupCode);
        }
    }

    $output = run_cmd($root, 'git pull --ff-only origin main', $code);
    if ($code !== 0) {
        throw new RuntimeException('git pull failed: ' . $output);
    }

    $output = run_cmd(
        $root,
        php_command('scripts/build-lamp.php', '.', substr($remote, 0, 12)),
        $code
    );
    if ($code !== 0) {
        throw new RuntimeException('Live LAMP asset build failed: ' . $output);
    }

    $deployed = trim(run_cmd($root, 'git rev-parse HEAD', $code));
    if ($code !== 0 || !preg_match('/^[0-9a-f]{40}$/', $deployed)) {
        throw new RuntimeException('Unable to resolve deployed commit.');
    }

    respond(200, [
        'ok' => true,
        'status' => 'deployed',
        'changed' => true,
        'previousCommit' => $local,
        'commit' => $deployed,
        'startedAt' => $startedAt,
        'completedAt' => gmdate('c'),
        'runtime' => 'rocky9-lamp',
        'starCommsSecretConfigured' => $secretState['configured'],
        'starCommsSecretUpdated' => $secretState['updated'],
        'message' => 'DNI origin/main was verified and deployed through the existing Rocky Linux 9 Apache/PHP stack.'
    ]);
} catch (Throwable $error) {
    respond(500, [
        'ok' => false,
        'status' => 'failed',
        'startedAt' => $startedAt,
        'completedAt' => gmdate('c'),
        'runtime' => 'rocky9-lamp',
        'error' => 'DNI deployment failed.',
        'detail' => substr($error->getMessage(), -4000)
    ]);
} finally {
    if (is_resource($lock)) {
        flock($lock, LOCK_UN);
        fclose($lock);
    }
}
