#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${DNI_APP_DIR:-/opt/dni-terminal}"
DB_NAME="dni_terminal"
DB_USER="dni_app"
DB_HOST="127.0.0.1"
RUNTIME_DIR="$APP_DIR/data"
RUNTIME_ENV="$RUNTIME_DIR/dni-runtime.env"
MIGRATIONS_DIR="$APP_DIR/database/migrations"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this database initializer as root."
  exit 1
fi

for command_name in mariadb openssl mktemp install awk grep; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "[database] Required existing command is missing: $command_name"
    echo "[database] No package manager will be run automatically."
    exit 1
  fi
done

if [ ! -d "$MIGRATIONS_DIR" ] || ! compgen -G "$MIGRATIONS_DIR/*.sql" >/dev/null; then
  echo "[database] No migration files found in $MIGRATIONS_DIR"
  exit 1
fi

if ! id apache >/dev/null 2>&1; then
  echo "[database] Existing Apache account 'apache' was not found."
  exit 1
fi

echo "[database] Verifying local MariaDB administrative access"
if ! mariadb --protocol=socket --batch --skip-column-names -e 'SELECT VERSION();' >/dev/null 2>&1; then
  echo "[database] Local root/socket access to MariaDB failed."
  echo "[database] Run this initializer from the VPS root account with local MariaDB administrative access."
  exit 1
fi

DB_PASSWORD="$(openssl rand -hex 32)"

mariadb --protocol=socket <<SQL
CREATE DATABASE IF NOT EXISTS ${DB_NAME}
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${DB_USER}'@'${DB_HOST}' IDENTIFIED BY '${DB_PASSWORD}';
ALTER USER '${DB_USER}'@'${DB_HOST}' IDENTIFIED BY '${DB_PASSWORD}';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX
  ON ${DB_NAME}.*
  TO '${DB_USER}'@'${DB_HOST}';

FLUSH PRIVILEGES;
SQL

echo "[database] Applying DNI migrations with administrative access"
for migration in "$MIGRATIONS_DIR"/*.sql; do
  echo "[database] -> $(basename "$migration")"
  mariadb --protocol=socket "$DB_NAME" < "$migration"
done

mkdir -p "$RUNTIME_DIR"
TEMP_ENV="$(mktemp "$RUNTIME_DIR/dni-runtime.XXXXXX")"
trap 'rm -f "$TEMP_ENV"' EXIT

if [ -f "$RUNTIME_ENV" ]; then
  awk '
    !/^DNI_DB_DSN=/ &&
    !/^DNI_DB_USER=/ &&
    !/^DNI_DB_PASSWORD=/
  ' "$RUNTIME_ENV" > "$TEMP_ENV"
fi

{
  if [ -s "$TEMP_ENV" ]; then
    printf '\n'
  fi
  printf '# DNI MariaDB application connection. Generated by database/install-rocky.sh.\n'
  printf 'DNI_DB_DSN=mysql:host=127.0.0.1;port=3306;dbname=dni_terminal;charset=utf8mb4\n'
  printf 'DNI_DB_USER=dni_app\n'
  printf 'DNI_DB_PASSWORD=%s\n' "$DB_PASSWORD"
} >> "$TEMP_ENV"

install -o apache -g apache -m 0600 "$TEMP_ENV" "$RUNTIME_ENV"
rm -f "$TEMP_ENV"
trap - EXIT

if [ -f "$APP_DIR/scripts/migrate.php" ]; then
  echo "[database] Registering migrations for automatic deploy-time updates"
  MIGRATION_RESULT="$(php "$APP_DIR/scripts/migrate.php")"
  echo "[database] $MIGRATION_RESULT"
fi

if ! php -r '
  $path=$argv[1];
  $env=[];
  foreach(file($path, FILE_IGNORE_NEW_LINES) ?: [] as $line){
    $line=trim($line);
    if($line==="" || str_starts_with($line,"#")) continue;
    $pos=strpos($line,"=");
    if($pos===false) continue;
    $env[substr($line,0,$pos)]=substr($line,$pos+1);
  }
  $pdo=new PDO($env["DNI_DB_DSN"],$env["DNI_DB_USER"],$env["DNI_DB_PASSWORD"],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
  $permissions=(int)$pdo->query("SELECT COUNT(*) FROM dni_permissions")->fetchColumn();
  $sectors=(int)$pdo->query("SELECT COUNT(*) FROM dni_sectors WHERE active=TRUE")->fetchColumn();
  $services=(int)$pdo->query("SELECT COUNT(*) FROM dni_service_types WHERE active=TRUE")->fetchColumn();
  $migrationTable=(int)$pdo->query("SELECT COUNT(*) FROM dni_schema_migrations")->fetchColumn();
  exit($permissions > 0 && $sectors > 0 && $services > 0 && $migrationTable > 0 ? 0 : 1);
' "$RUNTIME_ENV"; then
  echo "[database] DNI application database verification failed."
  exit 1
fi

echo "[database] DNI MariaDB database is ready for automatic deploy-time migrations."
echo "[database] Application credentials were written to $RUNTIME_ENV with mode 0600."
echo "[database] The dni_app account is limited to this database and has only SELECT/INSERT/UPDATE/DELETE plus CREATE/ALTER/INDEX for schema migrations."
echo "[database] No database password was printed or committed to Git."
