#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${DNI_APP_DIR:-/opt/dni-terminal}"
RUNTIME_DIR="$APP_DIR/data"
RUNTIME_ENV="$RUNTIME_DIR/dni-runtime.env"
SQLITE_DB="$RUNTIME_DIR/dni_terminal.db"
CANONICAL_MIGRATION_RUNNER="$APP_DIR/scripts/database/migrate.php"
COMPAT_MIGRATION_RUNNER="$APP_DIR/scripts/migrate.php"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this database initializer as root."
  exit 1
fi

for command_name in install awk grep php runuser; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "[database] Required existing command is missing: $command_name"
    echo "[database] No package manager will be run automatically."
    exit 1
  fi
done

if ! id apache >/dev/null 2>&1; then
  echo "[database] Existing Apache account 'apache' was not found."
  exit 1
fi

if ! php -r 'exit(extension_loaded("pdo_sqlite") ? 0 : 1);'; then
  echo "[database] PHP pdo_sqlite is not enabled."
  echo "[database] DNI Terminal requires PDO SQLite; no package manager will be run automatically."
  exit 1
fi

MIGRATION_RUNNER=""
if [ -f "$CANONICAL_MIGRATION_RUNNER" ]; then
  MIGRATION_RUNNER="$CANONICAL_MIGRATION_RUNNER"
elif [ -f "$COMPAT_MIGRATION_RUNNER" ]; then
  MIGRATION_RUNNER="$COMPAT_MIGRATION_RUNNER"
else
  echo "[database] DNI SQLite migration/initializer script was not found."
  exit 1
fi

install -d -o apache -g apache -m 0750 "$RUNTIME_DIR"
TEMP_ENV="$(mktemp "$RUNTIME_DIR/dni-runtime.XXXXXX")"
trap 'rm -f "$TEMP_ENV"' EXIT

if [ -f "$RUNTIME_ENV" ]; then
  awk '
    !/^DNI_DB_DSN=/ &&
    !/^DNI_DB_USER=/ &&
    !/^DNI_DB_PASSWORD=/ &&
    !/^DNI_SQLITE_PATH=/
  ' "$RUNTIME_ENV" > "$TEMP_ENV"
fi

{
  if [ -s "$TEMP_ENV" ]; then
    printf '\n'
  fi
  printf '# DNI authoritative SQLite database. Generated by database/tools/install-rocky.sh.\n'
  printf 'DNI_SQLITE_PATH=%s\n' "$SQLITE_DB"
} >> "$TEMP_ENV"

install -o apache -g apache -m 0600 "$TEMP_ENV" "$RUNTIME_ENV"
rm -f "$TEMP_ENV"
trap - EXIT

echo "[database] Initializing authoritative SQLite database"
MIGRATION_RESULT="$(runuser -u apache -- php "$MIGRATION_RUNNER")"
echo "[database] $MIGRATION_RESULT"

if [ ! -f "$SQLITE_DB" ]; then
  echo "[database] SQLite database was not created: $SQLITE_DB"
  exit 1
fi

chown apache:apache "$SQLITE_DB"
chmod 0600 "$SQLITE_DB"

if ! runuser -u apache -- php -r '
$path=$argv[1];
$pdo=new PDO("sqlite:".$path,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$integrity=(string)$pdo->query("PRAGMA integrity_check")->fetchColumn();
$store=(int)$pdo->query("SELECT COUNT(*) FROM dni_store WHERE id=1")->fetchColumn();
exit($integrity === "ok" && $store === 1 ? 0 : 1);
' "$SQLITE_DB"; then
  echo "[database] DNI SQLite verification failed."
  exit 1
fi

echo "[database] DNI SQLite database is ready: $SQLITE_DB"
echo "[database] Database and runtime config are owned by apache and restricted to mode 0600."
echo "[database] Legacy MariaDB DNI_DB_* values were removed from $RUNTIME_ENV."
echo "[database] No package manager was run and no database credential was generated."
