const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const root = path.resolve(__dirname, '../..');
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const routing = read('public/src/js/routing.js');
const build = read('scripts/build/build-lamp.php');
const deploy = read('public/deploy.php');
const controller = read('server-http/operations-data.php');
const operations = read('server/php/dni-operations.php');
assert.ok(routing.includes("operations: '/operations'"));
assert.ok(routing.includes("case '/operations': return 'operations'"));
assert.ok(routing.includes('dni:operations-ready'));
assert.ok(build.includes("'admin', 'operations'"));
assert.ok(deploy.includes("'admin', 'operations'"));
assert.ok(deploy.includes("'/operations/'"));
assert.ok(controller.includes('dni_operations_staff_authorized($user)'));
assert.ok(operations.includes('$this->admin = dni_operations_staff_authorized($user)'));
assert.ok(operations.includes('operations.isb.read_restricted'));
const app = read('public/src/js/operations/operations-app.js');
assert.ok(app.includes('dni:operations-ready'));
assert.ok(app.includes('sessionError'));
assert.ok(read('public/src/js/authz.js').includes("'/operations'"));
execFileSync('php', [path.join(__dirname, 'verify-visibility.php')], {stdio:'inherit'});
execFileSync(process.execPath, [path.join(__dirname, 'verify-visibility.js')], {stdio:'inherit'});
console.log('DNI Operations routing, deployment and authorization checks passed.');
